language: python
python:
  - "2.7"
services:
  - rabbitmq
install:
  - pip install -r requirements.txt
before_script:
  - cp config.py.tmpl config.py
  - sudo -u postgres createdb iatidq
  - flask drop_db
  - flask init_db
  - flask refresh --minimal
script: "nosetests --exclude tests unittests/test_runtests.py unittests/test_summaryfn.py unittests/test_dataflows.py unittests/test_pipeline.py"
